### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mosaic-greg** [ajweeks/RaymarchingWorkshop#1]
Hi, great article :)
shadertoy won't allow the step below
![image](https://user-images.githubusercontent.com/12015938/59245849-780e3900-8c6e-11e9-9173-652aa146e21b.png)

**Comment by ajweeks** [comment]
Hi Greg,

That error is being caused by a subtraction between differing types; a `vec2` and a `vec3`. Because your input point `p` only has two components you probably want to subtract a `vec2`. Hope that helps!

-AJ

**Comment by huwb** [comment]
Actually it looks like that's my bad - i had that in the text in the 2D section. I've just updated it now. Apologies for that!
