### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by izzyreal** [ajweeks/RaymarchingWorkshop#3]
Would it be possible to add a glossary that maps the variables/arguments with short, cryptic names to their full names? For beginners like me that would be very helpful in understanding (and thus building on) what the code is doing.

**Comment by ajweeks** [comment]
Hey, sure thing 🙂 

I've created a draft here (the glossary is at the bottom of the page), could you let me know if I've covered everything?

https://github.com/electricsquare/raymarching-workshop/blob/86e73487688fdd5108a09c99246bf16e054bf31b/readme.md

**Comment by izzyreal** [comment]
@ajweeks Awesome, I've added a comment to https://github.com/electricsquare/raymarching-workshop/pull/4
